config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root "couriers#index", as: 'root'

    resources :couriers, expect: [:destroy]
    resources :packages, only: [:create]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
class Courier < ApplicationRecord

  has_many :packages, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }


end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :courier

  validates :tracking_number, presence: true, uniqueness: true
  validates :courier_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_courier
      @current_courier ||= Courier.find(session[:courier_id]) if session[:courier_id]
  end
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController
  before_action :set_category, only: %i[show update edit]
  before_action :set_courier, only: %i[show]

  def index
    @couriers = Courier.all
  end

  def show
    @packages = @courier.packages
  end

  def new
    @courier = Courier.new
  end

  def create
    @courier = Courier.new(courier_params)
    if @courier.save
      flash[:success] = 'Courier was successfully created!'
      redirect_to @courier
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @courier.update(courier_params)
      flash[:success] = 'Courier was successfully updated!'
      redirect_to @courier
    else
      render 'edit'
    end
  end

  private

  def courier_params
    params.require(:courier).permit(:name, :email)
  end

  def set_category
    @courier = Courier.find(params[:id])
  end

  def set_courier
    session[:courier_id] = @courier.id
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController

  def create
    @package = current_courier.packages.build(package_params)
    if @package.save
      flash[:success] = "Package was successfully created!"
      redirect_to current_courier
    else
      redirect_to current_courier
    end
  end

  private

  def package_params
    params.require(:package).permit(:tracking_number, :delivery_status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/couriers/_courier.html.erb
<div class="row justify-content-center">
  <div class="col-6 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
        <%= link_to courier.name, courier %>
      </div>
      <div class="card-body">
        <%= link_to "View profile", courier, class: "btn btn-outline-success" %>
        <%= link_to "Edit profile", edit_courier_path(courier), class: "btn btn-outline-info" %>
      </div>
    </div>
  </div>
</div>

app/views/couriers/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <%= render 'shared/error_messages', obj: @courier %>
      <%= form_with(model: @courier, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, class: "col-2 col-form-label text-light" %>
          <div class="col-8">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-8">
            <%= f.email_field :email, rows: 10, class: "form-control shadow rounded", placeholder: "Enter email address" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit(@courier.new_record? ? "Create courier" : "Update courier", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to couriers ]', :couriers, class: "text-info" %>
    </div>
  </div>
</div>

app/views/couriers/edit.html.erb
<h1 class="text-center mt-4">Edit courier</h1>
<%= render 'form' %>

app/views/couriers/index.html.erb
<h1 class="text-center mt-4">Couriers</h1>
<div class="container">
  <%= render @couriers %>
</div>
<%= link_to "Create new courier", new_courier_path, class: "dropdown-item" %>

app/views/couriers/new.html.erb
<h1 class="text-center mt-4">Create courier</h1>
<%= render 'form' %>

app/views/couriers/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <h1 class="text-center mt-4">
      <%= @courier.name %>'s profile
    </h1>
    <div class="text-center mt-4">
      <%= link_to "Edit your profile", edit_courier_path(@courier), class: "btn btn-outline-info" %>
    </div>
    <div class="text-center mt-4">
      <%= link_to 'Return to couriers', :couriers, class: "text-info" %>
    </div>
    <%= render 'shared/package_form' %>
  </aside>
  <div class="col-md-8">
    <% if @courier.packages.any? %>
      <h3>Packages (<%= @courier.packages.count %>)</h3>
      <ol class="packages">
        <%= render @packages %>
      </ol>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Delivery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_package_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/error_messages', obj: @package %>
      <%= form_with(model: @package, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :tracking_number, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :tracking_number, class: "form-control shadow rounded", placeholder: "Enter a tracking number" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :delivery_status, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.check_box :delivery_status, class: "form-control shadow rounded" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit('Create package', class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
  </div>
</div>